import fs from "fs";
import { v4 } from "uuid";

const items = [
  {
    id: 1,
    tag: "Suggested for you",
    isVerified: true,
    username: "virat.kohli",
    fullName: "Virat Kohli",
    profilePic: "images/users/virat.kohli.webp",
    hasStory: false,
  },
  {
    id: 21,
    tag: "Popular",
    isVerified: true,
    username: "yoyohoneysingh",
    fullName: "Yo Yo Honey Singh",
    profilePic: "images/users/yoyohoneysingh.webp",
    hasStory: true,
  },
  {
    id: 4112,
    tag: "Suggested for you",
    isVerified: true,
    username: "amansharma_0000",
    fullName: "Aman Sharma",
    profilePic: "images/users/amansharma_0000.webp",
    hasStory: false,
  },
  {
    id: 6132,
    tag: "Popular",
    isVerified: true,
    username: "instagram",
    fullName: "Instagram",
    profilePic: "images/users/instagram.webp",
    hasStory: false,
  },
  {
    id: 81,
    tag: "Suggested for you",
    isVerified: true,
    username: "elvish_yadav",
    fullName: "Elvish Raosahab",
    profilePic: "images/users/elvish_yadav.webp",
    hasStory: false,
  },
  {
    id: 51701,
    tag: "Suggested for you",
    isVerified: true,
    username: "trolls_official",
    fullName: "Trolls Official",
    profilePic: "images/users/trolls_official.webp",
    hasStory: true,
  },
  {
    id: 121,
    tag: "Suggested for you",
    isVerified: true,
    username: "joji_thampi",
    fullName: "Joji yoohanon thampi",
    profilePic: "images/users/joji_thampi.webp",
    hasStory: false,
  },
  {
    id: 141,
    tag: "Suggested for you",
    isVerified: true,
    username: "saketgokhale",
    fullName: "Saket Gokhale",
    profilePic: "images/users/saketgokhale.webp",
    hasStory: false,
  },
  {
    id: 161,
    tag: "Popular",
    isVerified: true,
    username: "itsmezidaanmerijaan",
    fullName: "Shahid Shaikh",
    profilePic: "images/users/itsmezidaanmerijaan.webp",
    hasStory: false,
  },
  {
    id: 181,
    tag: "Popular",
    isVerified: true,
    username: "mdshami.11",
    fullName: "𝕸𝖔𝖍𝖆𝖒𝖒𝖆𝖉 𝖘𝖍𝖆𝖒𝖎",
    profilePic: "images/users/mdshami.11.webp",
    hasStory: true,
  },
  {
    id: 201,
    tag: "Popular",
    isVerified: false,
    username: "vikas__gupta___07",
    fullName: "Vikas gupta",
    profilePic: "images/users/vikas__gupta___07.webp",
    hasStory: false,
  },
  {
    id: 220,
    tag: "Suggested for you",
    isVerified: true,
    username: "rvcjinsta",
    fullName: "RVCJ Media",
    profilePic: "images/users/rvcjinsta.webp",
    hasStory: false,
  },
  {
    id: 240,
    tag: "Popular",
    isVerified: true,
    username: "mrbeast",
    fullName: "MrBeast",
    profilePic: "images/users/mrbeast.webp",
    hasStory: true,
  },
  {
    id: 260,
    tag: "Popular",
    isVerified: true,
    username: "zayn.saifi2",
    fullName: "Zayn Saifi",
    profilePic: "images/users/zayn.saifi2.webp",
    hasStory: true,
  },
  {
    id: 280,
    tag: "Popular",
    isVerified: true,
    username: "amitabhbachchan",
    fullName: "Amitabh Bachchan",
    profilePic: "images/users/amitabhbachchan.webp",
    hasStory: false,
  },
  {
    id: 300,
    tag: "Popular",
    isVerified: true,
    username: "shahidkapoor",
    fullName: "Shahid Kapoor",
    profilePic: "images/users/shahidkapoor.webp",
    hasStory: false,
  },
  {
    id: 320,
    tag: "Suggested for you",
    isVerified: true,
    username: "aishwaryaraibachchan",
    fullName: "AishwaryaRaiBachchan",
    profilePic: "images/users/aishwaryaraibachchan_arb.webp",
    hasStory: false,
  },
  {
    id: 340,
    tag: "Suggested for you",
    isVerified: true,
    username: "viralbhayani",
    fullName: "Viral Bhayani",
    profilePic: "images/users/viralbhayani.webp",
    hasStory: true,
  },
  {
    id: 360,
    tag: "Popular",
    isVerified: true,
    username: "ranveersingh",
    fullName: "Ranveer Singh",
    profilePic: "images/users/ranveersingh.webp",
    hasStory: true,
  },
  {
    id: 380,
    tag: "Suggested for you",
    isVerified: true,
    username: "myogi_adityanath",
    fullName: "Shri Yogi Adityanath",
    profilePic: "images/users/myogi_adityanath.webp",
    hasStory: true,
  },
  {
    id: 400,
    tag: "Popular",
    isVerified: true,
    username: "srushtideshmukhias",
    fullName: "Srushti Deshmukh Gowda",
    profilePic: "images/users/srushtideshmukhias.webp",
    hasStory: false,
  },
  {
    id: 420,
    tag: "Popular",
    isVerified: true,
    username: "norafatehi",
    fullName: "Nora Fatehi",
    profilePic: "images/users/norafatehi.webp",
    hasStory: false,
  },
  {
    id: 440,
    tag: "Suggested for you",
    isVerified: true,
    username: "mr_faisu_07",
    fullName: "FAISAL SHAIKH",
    profilePic: "images/users/mr_faisu_07.webp",
    hasStory: true,
  },
  {
    id: 460,
    tag: "Suggested for you",
    isVerified: true,
    username: "rohittt_09_",
    fullName: "𝐑𝐨𝐡𝐢𝐭 𝐙𝐢𝐧𝐣𝐮𝐫𝐤𝐞 🇮🇳",
    profilePic: "images/users/rohittt_09_.webp",
    hasStory: false,
  },
  {
    id: 480,
    tag: "Popular",
    isVerified: true,
    username: "dharmendra_bilotia_",
    fullName: "Dharmendra Bilotia",
    profilePic: "images/users/dharmendra_bilotia_.webp",
    hasStory: false,
  },
  {
    id: 500,
    tag: "Popular",
    isVerified: true,
    username: "anushkasharma",
    fullName: "AnushkaSharma1588",
    profilePic: "images/users/anushkasharma.webp",
    hasStory: false,
  },
  {
    id: 520,
    tag: "Popular",
    isVerified: true,
    username: "theshubhankarmishra",
    fullName: "Shubhankar Mishra",
    profilePic: "images/users/theshubhankarmishra.webp",
    hasStory: false,
  },
  {
    id: 540,
    tag: "Suggested for you",
    isVerified: true,
    username: "mohammedsirajofficial",
    fullName: "Mohammed Siraj",
    profilePic: "images/users/mohammedsirajofficial.webp",
    hasStory: true,
  },
  {
    id: 560,
    tag: "Suggested for you",
    isVerified: true,
    username: "bhajanmarg_official",
    fullName: "Bhajan Marg Official",
    profilePic: "images/users/bhajanmarg_official.webp",
    hasStory: false,
  },
  {
    id: 580,
    tag: "Suggested for you",
    isVerified: true,
    username: "voompla",
    fullName: "Voompla",
    profilePic: "images/users/voompla.webp",
    hasStory: false,
  },
  {
    id: 31,
    tag: "Suggested for you",
    isVerified: true,
    username: "aashimehra29",
    fullName: "Aashimehra29",
    profilePic: "images/users/aashimehra29.webp",
    hasStory: true,
  },
  {
    id: 32,
    tag: "Suggested for you",
    isVerified: false,
    username: "abhishek_mens_parlar",
    fullName: "Abhishek Mens Parlar",
    profilePic: "images/users/abhishek_mens_parlar.webp",
    hasStory: false,
  },
  {
    id: 33,
    tag: "Suggested for you",
    isVerified: true,
    username: "aishwaryaraibachchan_arb",
    fullName: "Aishwaryaraibachchan Arb",
    profilePic: "images/users/aishwaryaraibachchan_arb.webp",
    hasStory: true,
  },
  {
    id: 34,
    tag: "Suggested for you",
    isVerified: false,
    username: "ai_doctor_sahab",
    fullName: "Ai Doctor Sahab",
    profilePic: "images/users/ai_doctor_sahab.webp",
    hasStory: false,
  },
  {
    id: 35,
    tag: "Suggested for you",
    isVerified: true,
    username: "alluarjunenthusiast",
    fullName: "Alluarjunenthusiast",
    profilePic: "images/users/alluarjunenthusiast.webp",
    hasStory: false,
  },
  {
    id: 36,
    tag: "Suggested for you",
    isVerified: true,
    username: "alluarjunonline",
    fullName: "Alluarjunonline",
    profilePic: "images/users/alluarjunonline.webp",
    hasStory: true,
  },
  {
    id: 40,
    tag: "Suggested for you",
    isVerified: true,
    username: "autoboyravi",
    fullName: "Autoboyravi",
    profilePic: "images/users/autoboyravi.webp",
    hasStory: false,
  },
  {
    id: 41,
    tag: "Suggested for you",
    isVerified: true,
    username: "baji_2020_",
    fullName: "Baji 2020 ",
    profilePic: "images/users/baji_2020_.webp",
    hasStory: true,
  },
  {
    id: 43,
    tag: "Suggested for you",
    isVerified: false,
    username: "bourbonfinds",
    fullName: "Bourbonfinds",
    profilePic: "images/users/bourbonfinds.webp",
    hasStory: true,
  },
  {
    id: 44,
    tag: "Suggested for you",
    isVerified: false,
    username: "cristiano",
    fullName: "Cristiano",
    profilePic: "images/users/cristiano.webp",
    hasStory: false,
  },
  {
    id: 45,
    tag: "Suggested for you",
    isVerified: true,
    username: "danceronbike",
    fullName: "Danceronbike",
    profilePic: "images/users/danceronbike.webp",
    hasStory: true,
  },
  {
    id: 47,
    tag: "Suggested for you",
    isVerified: false,
    username: "diljitdosanjh",
    fullName: "Diljitdosanjh",
    profilePic: "images/users/diljitdosanjh.webp",
    hasStory: false,
  },
  {
    id: 49,
    tag: "Suggested for you",
    isVerified: false,
    username: "fadiiyyyy",
    fullName: "Fadiiyyyy",
    profilePic: "images/users/fadiiyyyy.webp",
    hasStory: false,
  },
  {
    id: 50,
    tag: "Suggested for you",
    isVerified: true,
    username: "filmi.feelings",
    fullName: "Filmi Feelings",
    profilePic: "images/users/filmi.feelings.webp",
    hasStory: false,
  },
  {
    id: 51,
    tag: "Suggested for you",
    isVerified: true,
    username: "gais_edits_",
    fullName: "Gais Edits ",
    profilePic: "images/users/gais_edits_.webp",
    hasStory: true,
  },
  {
    id: 52,
    tag: "Suggested for you",
    isVerified: false,
    username: "geneliad",
    fullName: "Geneliad",
    profilePic: "images/users/geneliad.webp",
    hasStory: false,
  },
  {
    id: 53,
    tag: "Suggested for you",
    isVerified: true,
    username: "hardikpandya93",
    fullName: "Hardikpandya93",
    profilePic: "images/users/hardikpandya93.webp",
    hasStory: true,
  },
  {
    id: 54,
    tag: "Suggested for you",
    isVerified: true,
    username: "ig_jonathangaming",
    fullName: "Ig Jonathangaming",
    profilePic: "images/users/ig_jonathangaming.webp",
    hasStory: false,
  },
  {
    id: 56,
    tag: "Suggested for you",
    isVerified: false,
    username: "instantbollywood",
    fullName: "Instantbollywood",
    profilePic: "images/users/instantbollywood.webp",
    hasStory: false,
  },
  {
    id: 59,
    tag: "Suggested for you",
    isVerified: false,
    username: "josepheaton1111",
    fullName: "Josepheaton1111",
    profilePic: "images/users/josepheaton1111.webp",
    hasStory: false,
  },
  {
    id: 60,
    tag: "Suggested for you",
    isVerified: true,
    username: "ladbible",
    fullName: "Ladbible",
    profilePic: "images/users/ladbible.webp",
    hasStory: true,
  },
  {
    id: 61,
    tag: "Suggested for you",
    isVerified: true,
    username: "lil_mvvx",
    fullName: "Lil Mvvx",
    profilePic: "images/users/lil_mvvx.webp",
    hasStory: true,
  },
  {
    id: 62,
    tag: "Suggested for you",
    isVerified: false,
    username: "ludacris",
    fullName: "Ludacris",
    profilePic: "images/users/ludacris.webp",
    hasStory: false,
  },
  {
    id: 63,
    tag: "Suggested for you",
    isVerified: true,
    username: "machines_in_action",
    fullName: "Machines In Action",
    profilePic: "images/users/machines_in_action.webp",
    hasStory: true,
  },
  {
    id: 65,
    tag: "Suggested for you",
    isVerified: true,
    username: "mercurymover",
    fullName: "Mercurymover",
    profilePic: "images/users/mercurymover.webp",
    hasStory: true,
  },
  {
    id: 68,
    tag: "Suggested for you",
    isVerified: true,
    username: "mr_azmaik",
    fullName: "Mr Azmaik",
    profilePic: "images/users/mr_azmaik.webp",
    hasStory: false,
  },
  {
    id: 70,
    tag: "Suggested for you",
    isVerified: true,
    username: "msh_fam",
    fullName: "Msh Fam",
    profilePic: "images/users/msh_fam.webp",
    hasStory: false,
  },
  {
    id: 73,
    tag: "Suggested for you",
    isVerified: false,
    username: "official_sukha_bouncer",
    fullName: "Official Sukha Bouncer",
    profilePic: "images/users/official_sukha_bouncer.webp",
    hasStory: false,
  },
  {
    id: 74,
    tag: "Suggested for you",
    isVerified: true,
    username: "otnifil",
    fullName: "Otnifil",
    profilePic: "images/users/otnifil.webp",
    hasStory: false,
  },
  {
    id: 75,
    tag: "Suggested for you",
    isVerified: false,
    username: "puzzlesinlove",
    fullName: "Puzzlesinlove",
    profilePic: "images/users/puzzlesinlove.webp",
    hasStory: true,
  },
  {
    id: 76,
    tag: "Suggested for you",
    isVerified: true,
    username: "raj_karanjacha",
    fullName: "Raj Karanjacha",
    profilePic: "images/users/raj_karanjacha.webp",
    hasStory: true,
  },
  {
    id: 78,
    tag: "Suggested for you",
    isVerified: true,
    username: "reelzinlife",
    fullName: "Reelzinlife",
    profilePic: "images/users/reelzinlife.webp",
    hasStory: false,
  },
  {
    id: 79,
    tag: "Suggested for you",
    isVerified: true,
    username: "ritik_raushan76",
    fullName: "Ritik Raushan76",
    profilePic: "images/users/ritik_raushan76.webp",
    hasStory: true,
  },
  {
    id: 82,
    tag: "Suggested for you",
    isVerified: false,
    username: "sachintendulkar",
    fullName: "Sachintendulkar",
    profilePic: "images/users/sachintendulkar.webp",
    hasStory: true,
  },
  {
    id: 86,
    tag: "Suggested for you",
    isVerified: true,
    username: "techat6",
    fullName: "Techat6",
    profilePic: "images/users/techat6.webp",
    hasStory: true,
  },
  {
    id: 88,
    tag: "Suggested for you",
    isVerified: false,
    username: "the_masta01",
    fullName: "The Masta01",
    profilePic: "images/users/the_masta01.webp",
    hasStory: true,
  },
  {
    id: 89,
    tag: "Suggested for you",
    isVerified: true,
    username: "the_travelling_soul",
    fullName: "The Travelling Soul",
    profilePic: "images/users/the_travelling_soul.webp",
    hasStory: false,
  },
  {
    id: 90,
    tag: "Suggested for you",
    isVerified: true,
    username: "trishakrishnan",
    fullName: "Trishakrishnan",
    profilePic: "images/users/trishakrishnan.webp",
    hasStory: false,
  },
  {
    id: 92,
    tag: "Suggested for you",
    isVerified: true,
    username: "v4u_groups",
    fullName: "V4u Groups",
    profilePic: "images/users/v4u_groups.webp",
    hasStory: false,
  },
  {
    id: 96,
    tag: "Suggested for you",
    isVerified: false,
    username: "vivekvermaa01",
    fullName: "Vivekvermaa01",
    profilePic: "images/users/vivekvermaa01.webp",
    hasStory: true,
  },
  {
    id: 97,
    tag: "Suggested for you",
    isVerified: false,
    username: "voodoovixenldn",
    fullName: "Voodoovixenldn",
    profilePic: "images/users/voodoovixenldn.webp",
    hasStory: true,
  },
  {
    id: 99,
    tag: "Suggested for you",
    isVerified: true,
    username: "vyshnax_",
    fullName: "Vyshnax ",
    profilePic: "images/users/vyshnax_.webp",
    hasStory: false,
  },
  {
    id: 100,
    tag: "Suggested for you",
    isVerified: true,
    username: "yadav_168",
    fullName: "Yadav 168",
    profilePic: "images/users/yadav_168.webp",
    hasStory: true,
  },
  {
    id: 101,
    tag: "Suggested for you",
    isVerified: false,
    username: "your_love_ankit",
    fullName: "Your Love Ankit",
    profilePic: "images/users/your_love_ankit.webp",
    hasStory: true,
  },
  {
    id: 103,
    tag: "Suggested for you",
    isVerified: true,
    username: "yp_creation792",
    fullName: "Yp Creation792",
    profilePic: "images/users/yp_creation792.webp",
    hasStory: true,
  },
  {
    id: 104,
    tag: "Suggested for you",
    isVerified: true,
    username: "ysjagantimes",
    fullName: "Ysjagantimes",
    profilePic: "images/users/ysjagantimes.webp",
    hasStory: false,
  },
  {
    id: 121785,
    tag: "Popular",
    isVerified: true,
    username: "aliaabhatt",
    fullName: "Alia Bhatt",
    profilePic: "images/users/aliaabhatt.webp",
    hasStory: false,
  },
  {
    id: 6785,
    tag: "Suggested for you",
    isVerified: false,
    username: "1sometrics",
    fullName: "Lakhin",
    profilePic: "images/users/1sometrics.webp",
    hasStory: true,
  },
  {
    id: 106,
    tag: "Suggested for you",
    isVerified: false,
    username: "ze__ta",
    fullName: "Ze  Ta",
    profilePic: "images/users/ze__ta.webp",
    hasStory: true,
  },
  {
    id: 107,
    tag: "Suggested for you",
    isVerified: true,
    username: "__whois_deep_",
    fullName: "  Whois Deep ",
    profilePic: "images/users/__whois_deep_.webp",
    hasStory: true,
  },
];

const formattedItems = items.map((item) => ({
  ...item,
  id: v4(),
}));

fs.writeFileSync("formatted.json", JSON.stringify(formattedItems, null, 2));
